name: Android CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo ${{ env.tag }}

      - name: Run KtLint
        run: ./gradlew ktlintCheck

      - name: Build Debug APK
        id: build
        run: ./gradlew assembleDebug

      - uses: ilharp/sign-android-release@v1 # Or use @nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/debug
          signingKey: ${{ secrets.APP_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.APP_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.APP_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.APP_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: ${{ steps.sign_app.outputs.signedFile }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.sign_app.outputs.signedFile }}
          token: ${{ secrets.TOKEN }}
